name: ToolsPlus
main: ToolsPlus\main
description: A plugin that'll give your server more features.
version: 1.0.0
author: BouncyJeffer
api: [3.0.0, 3.0.0-ALPHA4]
load: POSTWORLD
commands:
 heal:
  description: Heal a player
  usage: "/heal <player>"
  permission: toolsplus.heal
 xyz:
  description: View your X, Y and Z coordinates.
  usage: "/xyz"
  permission: toolsplus.xyz
 alert:
  description: Send an alert to the entire server.
  usage: "/alert <message>"
  permission: toolsplus.alert
 kickall:
  description: Kicks all other players off the server.
  usage: "/kickall"
  permission: toolsplus.kickall
permissions:
 toolsplus.heal:
  description: Permission to heal players.
  default: true
 toolsplus.xyz:
  description: Permission to view your X, Y and Z coordinates.
  default: true
 toolsplus.alert:
  description: Permission to send server wide alerts
  default: false
 toolsplus.kickall:
  description: Permission to kick all players offline.
  default: false
